# config/storage.yml

# Lưu file trên máy tính khi phát triển
local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Lưu file khi chạy test
test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

# Lưu file lên Amazon S3 (production)
amazon:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: <%= ENV['AWS_REGION'] %>
  bucket: <%= ENV['AWS_BUCKET'] %>
